import { Event, User } from './types';

// Mock user data
export const mockUser: User = {
  id: '1',
  name: 'Kevin Logan',
  email: 'kevin@example.com',
  role: 'admin',
  favoriteTeams: ['Lakers', 'Patriots', 'Real Madrid'],
};

// Mock events data
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Lakers vs Warriors',
    sport: 'Basketball',
    status: 'live',
    date: '2025-10-29',
    time: '19:30',
    venue: 'Crypto.com Arena',
    homeTeam: 'Lakers',
    awayTeam: 'Warriors',
    homeScore: 98,
    awayScore: 95,
    description: 'Western Conference showdown',
    attendees: 18997,
    maxCapacity: 19000,
  },
  {
    id: '2',
    title: 'Patriots vs Chiefs',
    sport: 'Football',
    status: 'upcoming',
    date: '2025-10-30',
    time: '20:15',
    venue: 'Gillette Stadium',
    homeTeam: 'Patriots',
    awayTeam: 'Chiefs',
    description: 'AFC Championship rematch',
    attendees: 0,
    maxCapacity: 65878,
  },
  {
    id: '3',
    title: 'Real Madrid vs Barcelona',
    sport: 'Soccer',
    status: 'upcoming',
    date: '2025-10-31',
    time: '15:00',
    venue: 'Santiago Bernabéu',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    description: 'El Clásico - La Liga',
    attendees: 81044,
    maxCapacity: 81044,
  },
  {
    id: '4',
    title: 'Yankees vs Red Sox',
    sport: 'Baseball',
    status: 'completed',
    date: '2025-10-28',
    time: '19:05',
    venue: 'Yankee Stadium',
    homeTeam: 'Yankees',
    awayTeam: 'Red Sox',
    homeScore: 7,
    awayScore: 4,
    description: 'AL East rivalry game',
    attendees: 47309,
    maxCapacity: 47309,
  },
  {
    id: '5',
    title: 'Celtics vs Heat',
    sport: 'Basketball',
    status: 'upcoming',
    date: '2025-10-30',
    time: '19:00',
    venue: 'TD Garden',
    homeTeam: 'Celtics',
    awayTeam: 'Heat',
    description: 'Eastern Conference matchup',
    attendees: 15234,
    maxCapacity: 19156,
  },
  {
    id: '6',
    title: 'Federer vs Nadal Exhibition',
    sport: 'Tennis',
    status: 'upcoming',
    date: '2025-11-01',
    time: '14:00',
    venue: 'Arthur Ashe Stadium',
    homeTeam: 'Federer',
    awayTeam: 'Nadal',
    description: 'Legends exhibition match',
    attendees: 23771,
    maxCapacity: 23771,
  },
  {
    id: '7',
    title: 'Cowboys vs Eagles',
    sport: 'Football',
    status: 'live',
    date: '2025-10-29',
    time: '20:20',
    venue: 'AT&T Stadium',
    homeTeam: 'Cowboys',
    awayTeam: 'Eagles',
    homeScore: 21,
    awayScore: 17,
    description: 'NFC East division game',
    attendees: 80000,
    maxCapacity: 80000,
  },
  {
    id: '8',
    title: 'Manchester United vs Liverpool',
    sport: 'Soccer',
    status: 'completed',
    date: '2025-10-27',
    time: '16:30',
    venue: 'Old Trafford',
    homeTeam: 'Manchester United',
    awayTeam: 'Liverpool',
    homeScore: 2,
    awayScore: 2,
    description: 'Premier League classic',
    attendees: 74879,
    maxCapacity: 74879,
  },
];
